### PR TITLE
npm install and npm run compile added to section 2. Install

### PR DESCRIPTION
**Pull request by programarivm**
Closes https://github.com/ExchangeUnion/xud/issues/673

`docker-compose.yml` might be tweaked in order to run `npm` through the containers.

### CODE REVIEW

**Comment by programarivm** [comment]
Not yet actually, just playing around. Thanks.

**Comment by kilrau** [comment]
Oh could you try that and confirm? We shouldn't have untested commands in our wiki...

**Comment by programarivm** [comment]
Atm, it looks as if `docker-compose.yml` assumes `npm` must run on the OS first.

On a different side note, this sequence of commands:
```
git clone https://github.com/ExchangeUnion/xud
cd xud
npm install
npm run compile
```
Causes https://github.com/ExchangeUnion/xud/pull/691

**Comment by kilrau** [comment]
> `docker-compose.yml` might be tweaked in order to run `npm` through the containers.

Yes, that's how it should be. We'll take care of thi soon. Closing this one.

**Pull request closed without merging**
